"""Safe execution of LLM-proposed feature functions.

The agent proposes Python source code defining a feature function with signature
    def <name>(panel: dict[str, pd.DataFrame]) -> pd.DataFrame
We validate the AST against a tight allowlist before exec'ing in a restricted
namespace. Anything outside the allowlist raises `UnsafeCodeError`.

Safety model (solo-researcher local tool):
  * No imports — `np` and `pd` are pre-injected into the exec namespace.
  * No filesystem / network / subprocess / eval / exec / compile.
  * No dunder attribute access, no dynamic attr via getattr/setattr/delattr.
  * No access to `__builtins__`, `globals`, `locals`, `vars`, `input`, etc.
  * Allowed builtins: a short whitelist of pure helpers (len, abs, range, ...).

This is "good enough" for code generated by Claude running on your own machine,
not a defense against a determined attacker. For stronger isolation use a
subprocess with resource limits.
"""
from __future__ import annotations

import ast
import builtins
from typing import Callable

import numpy as np
import pandas as pd


class UnsafeCodeError(Exception):
    """Raised when proposed code fails the AST safety check."""


_SAFE_BUILTIN_NAMES = (
    "abs",
    "all",
    "any",
    "bool",
    "dict",
    "enumerate",
    "filter",
    "float",
    "int",
    "isinstance",
    "len",
    "list",
    "map",
    "max",
    "min",
    "range",
    "reversed",
    "round",
    "set",
    "sorted",
    "str",
    "sum",
    "tuple",
    "zip",
)

_SAFE_BUILTINS = {name: getattr(builtins, name) for name in _SAFE_BUILTIN_NAMES}

_FORBIDDEN_NAMES = frozenset(
    [
        "__import__",
        "__builtins__",
        "breakpoint",
        "compile",
        "delattr",
        "eval",
        "exec",
        "getattr",
        "globals",
        "help",
        "input",
        "locals",
        "memoryview",
        "open",
        "setattr",
        "vars",
    ]
)


class _Validator(ast.NodeVisitor):
    def visit_Import(self, node: ast.Import) -> None:  # noqa: N802
        raise UnsafeCodeError("`import` statements are not allowed; use pre-injected np and pd")

    def visit_ImportFrom(self, node: ast.ImportFrom) -> None:  # noqa: N802
        raise UnsafeCodeError("`from ... import` is not allowed; use pre-injected np and pd")

    def visit_Attribute(self, node: ast.Attribute) -> None:  # noqa: N802
        if node.attr.startswith("__") and node.attr.endswith("__"):
            raise UnsafeCodeError(f"dunder attribute access forbidden: .{node.attr}")
        self.generic_visit(node)

    def visit_Name(self, node: ast.Name) -> None:  # noqa: N802
        if node.id in _FORBIDDEN_NAMES:
            raise UnsafeCodeError(f"forbidden name: {node.id}")
        self.generic_visit(node)

    def visit_Global(self, node: ast.Global) -> None:  # noqa: N802
        raise UnsafeCodeError("`global` is not allowed")

    def visit_Nonlocal(self, node: ast.Nonlocal) -> None:  # noqa: N802
        raise UnsafeCodeError("`nonlocal` is not allowed")


def exec_feature(source: str, expected_name: str | None = None) -> Callable:
    """Validate and exec a feature function source.

    Returns the resolved callable. The source must define at least one function;
    if `expected_name` is given, we return that function. Otherwise we require
    exactly one top-level function definition and return it.
    """
    try:
        tree = ast.parse(source)
    except SyntaxError as e:
        raise UnsafeCodeError(f"syntax error: {e}") from e

    _Validator().visit(tree)

    ns: dict[str, object] = {
        "__builtins__": _SAFE_BUILTINS,
        "np": np,
        "pd": pd,
    }
    code = compile(tree, f"<feature:{expected_name or 'anon'}>", "exec")
    exec(code, ns)  # noqa: S102 — sandboxed

    if expected_name is not None:
        fn = ns.get(expected_name)
        if not callable(fn):
            raise UnsafeCodeError(
                f"source did not define a callable named '{expected_name}'"
            )
        return fn  # type: ignore[return-value]

    candidates = [
        v
        for k, v in ns.items()
        if callable(v) and not k.startswith("_") and k not in {"np", "pd"}
    ]
    if len(candidates) != 1:
        raise UnsafeCodeError(
            f"expected exactly one top-level function, found {len(candidates)}"
        )
    return candidates[0]  # type: ignore[return-value]
